### ISSUE TITLE
Is this supposed to mimic pyrcc5 ?

### ISSUE THREAD

**Issue by someburner** [domarm-comat/pyqt6rc#5]
Was glad to see someone made a tool to generate rcc files, but why is it only for UI files? Could it easily be extended to mimic pyrcc5 behavior?

**Comment by someburner** [comment]
Looks like the QT6 `rcc` tool would do what I want. That said, I think a native python tool would be nice. Feel free to close if this is outside the scope of this project :)

**Comment by domarm-comat** [comment]
It would be great, I understand :).  

But as stated here: https://www.riverbankcomputing.com/static/Docs/PyQt6/pyqt5_differences.html, PyQt6 developers decided to remove resource support completely. Therefore there is no way to use `:/icons/icon.ico` notation.

Purpose of pyqt6rc is to at least provide some support for generation of .py files from .ui files. Maybe there is some way to use .zip file to package all resources and then use it in similar way as Qt resources. I can have a look at that in the future.

For now, if it's really crucial for your project to use Qt resources, I would switch to PySide6 as that seems to still support it: [https://doc.qt.io/qtforpython-6/tutorials/basictutorial/qrcfiles.html](https://doc.qt.io/qtforpython-6/tutorials/basictutorial/qrcfiles.html)

**Comment by someburner** [comment]
Yeah I don't really get it- PySide6-rcc worked for my scripts, but invoking QT6's packaged `rcc` binary and I get missing files.

Also, using QT5 generated qrc files appears to work perfectly fine with PyQT6. Quite frustrating to remove that, it's not a lot of code from what I saw..

**Comment by someburner** [comment]
Actually- the `rcc` binary does seem to work if I specify no compression. Maybe something with qfile.
